name: Site CI (NodeJS)

defaults:
  run:
    working-directory: Site

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build --if-present
